### ISSUE TITLE
REME.md错别字有点多

### ISSUE THREAD

**Issue by LinXiaoTao** [closedevice/FastApp#1]
1. “目前国内很多大神也在这些项目智商二次封装了很多使用的库”,"智商"？
2. "目前网络加载框架也是繁多，目前常用的有以下几种：ImageLoader（2011年），Picasso（2013年），Glide（2012年），Fresco（2015年）四种。",更严谨说是图片加载框架吧
3. “5年的时间，让Android整个生态环境更加晚上","晚上"?

**Comment by lionoggo** [comment]
嗯，多谢了，写点有点急
